# Generated by Django 4.2.27 on 2026-01-28 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Nazwa kategorii, np. Uczelnia.', max_length=50)),
                ('opis', models.TextField(blank=True, help_text='Opis kategorii (opcjonalnie).')),
                ('kolor', models.CharField(default='#000000', help_text='Kolor w HEX, np. #FF0000.', max_length=7)),
                ('owner', models.ForeignKey(help_text='Użytkownik, do którego należy kategoria.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Miejsce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Nazwa miejsca, np. Dom, Uczelnia.', max_length=120)),
                ('adres', models.CharField(blank=True, help_text='Adres (opcjonalnie).', max_length=255)),
                ('notatki', models.TextField(blank=True, help_text='Dodatkowe informacje (opcjonalnie).')),
                ('owner', models.ForeignKey(help_text='Użytkownik, do którego należy miejsce.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wydarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(help_text='Krótki tytuł, np. Kolokwium.', max_length=120)),
                ('opis', models.TextField(blank=True, help_text='Opis wydarzenia (opcjonalnie).')),
                ('start', models.DateTimeField(help_text='Data i godzina rozpoczęcia.')),
                ('koniec', models.DateTimeField(help_text='Data i godzina zakończenia.')),
                ('caly_dzien', models.BooleanField(default=False, help_text='Zaznacz, jeśli wydarzenie trwa cały dzień.')),
                ('status', models.CharField(choices=[('PLAN', 'Planowane'), ('DONE', 'Zrobione'), ('CANC', 'Odwołane')], default='PLAN', help_text='Status wydarzenia.', max_length=4)),
                ('priorytet', models.CharField(choices=[('LOW', 'Niski'), ('MED', 'Średni'), ('HIGH', 'Wysoki')], default='MED', help_text='Priorytet wydarzenia.', max_length=4)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('kategoria', models.ForeignKey(blank=True, help_text='Kategoria wydarzenia (opcjonalnie).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kalendarz.kategoria')),
                ('miejsce', models.ForeignKey(blank=True, help_text='Miejsce wydarzenia (opcjonalnie).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kalendarz.miejsce')),
                ('owner', models.ForeignKey(help_text='Użytkownik, do którego należy wydarzenie.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Przypomnienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiedy', models.DateTimeField(help_text='Kiedy wysłać przypomnienie (data i godzina).')),
                ('wiadomosc', models.CharField(blank=True, help_text='Treść przypomnienia (opcjonalnie).', max_length=200)),
                ('wyslane', models.BooleanField(default=False, help_text='Czy przypomnienie zostało już wysłane.')),
                ('wydarzenie', models.ForeignKey(help_text='Do jakiego wydarzenia.', on_delete=django.db.models.deletion.CASCADE, to='kalendarz.wydarzenie')),
            ],
            options={
                'ordering': ['kiedy'],
            },
        ),
    ]
