# Generated by Django 4.2.27 on 2026-01-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'ordering': ['nazwa']},
        ),
        migrations.AlterModelOptions(
            name='miejsce',
            options={'ordering': ['nazwa']},
        ),
        migrations.AlterField(
            model_name='kategoria',
            name='kolor',
            field=models.CharField(default='#000000', help_text='Kolor.', max_length=7),
        ),
    ]
